# Generated by Django 3.2.24 on 2024-03-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fggd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teyey', models.BigIntegerField()),
                ('reyeue', models.BigIntegerField()),
            ],
        ),
    ]
